Reverted `e5e550bf` `decodeString` in Bridge.request
In Python 3 `httplib.HTTPConnection.getresponse().read()` returns a
bytes stream, not a string. Therefore commit `e5e550bf` broke the
request parsing on Python 3:

```
>>> from phue import Bridge
>>> b = Bridge('hue')
>>> b.get_scene()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/blacklight/git_tree/phue/phue.py", line 1128, in get_scene
    return self.request('GET', '/api/' + self.username + '/scenes')
  File "/home/blacklight/git_tree/phue/phue.py", line 666, in request
    return json.loads(decodeString(response))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```